update_parameters() missing 1 required positional argument: 'exps'
Hi,
great project, thank you for maintaining it!

I found a small problem in the code:
`algo.update_parameters()` needs to receive the previously collected experiences to update its parameters.

This is the related error message:
```
    logs2 = algo.update_parameters()
TypeError: update_parameters() missing 1 required positional argument: 'exps'
```